version: '3'
services:
  extension-unique-id:
    image: martinopensky/kwil-extension-unique-id:latest
    ports:
      - 50055:50051
    restart: on-failure

  extension-db-export:
    image: martinopensky/kwil-extension-db-export:latest
    ports:
      - 50056:50052
    env_file:
      - ./config/extension-db-export.env
    restart: on-failure

  kwil:
    image: kwildb/kwil:latest
    ports:
      - 50051:50051
      - 50052:50052
      - 8080:8080
    env_file:
      - ./config/kwil.env
    environment:
      - KWILD_EXTENSION_ENDPOINTS=extension-unique-id:50051,extension-db-export:50052
    depends_on:
      - extension-unique-id
      - extension-db-export
    restart: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - kwil
    restart: on-failure
  
  # kwil-db-sync:
  #   image: kwil-db-sync:latest
  #   restart: on-failure