version: '3'
services:
  extension-helpers:
    image: kwil-extension-helpers:latest
    ports:
      - 40055:${EXTENSION_HELPERS_PORT}
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  extension-db-export:
    image: kwil-extension-db-export:latest
    ports:
      - 40056:${EXTENSION_DB_EXPORT_PORT}
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  extension-db-sync:
    image: kwil-extension-db-sync:latest
    volumes:
      - ./proto/db-sync.proto:/app/proto/db-sync.proto    
    ports:
      - 40057:${EXTENSION_DB_SYNC_PORT}
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  kwil-db-sync-server:
    image: kwil-db-sync-server:latest
    ports:
      - ${DB_SYNC_GRPC_PORT}:${DB_SYNC_GRPC_PORT}
    volumes:
      - ./proto/db-sync.proto:/app/proto/db-sync.proto
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  kwil-admin:
    image: kwil-admin:latest
    ports:
      - ${KWIL_ADMIN_PORT}:3000
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  kwil:
    image: kwildb/kwil:latest
    ports:
      - ${EXTENSION_HELPERS_PORT}:${EXTENSION_HELPERS_PORT}
      - ${EXTENSION_DB_EXPORT_PORT}:${EXTENSION_DB_EXPORT_PORT}
      - ${EXTENSION_DB_SYNC_PORT}:${EXTENSION_DB_SYNC_PORT}
      - ${KWIL_PROVIDER_PORT}:8080
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    environment:
      - KWILD_EXTENSION_ENDPOINTS=extension-helpers:${EXTENSION_HELPERS_PORT},extension-db-export:${EXTENSION_DB_EXPORT_PORT},extension-db-sync:${EXTENSION_DB_SYNC_PORT}
    depends_on:
      - extension-helpers
      - extension-db-export
      - extension-db-sync
    restart: on-failure