version: '3'
services:
  extension-helpers-2:
    image: martinopensky/kwil-extension-helpers:latest
    ports:
      - 50055:${EXTENSION_HELPERS_PORT}
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  extension-db-export-2:
    image: martinopensky/kwil-extension-db-export:latest
    ports:
      - 50056:${EXTENSION_DB_EXPORT_PORT}
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  extension-db-sync-2:
    image: martinopensky/kwil-extension-db-sync:latest
    volumes:
      - ./proto/db-sync.proto:/app/proto/db-sync.proto    
    ports:
      - 50057:${EXTENSION_DB_SYNC_PORT}
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  kwil-db-sync-server-2:
    image: martinopensky/kwil-db-sync-server:latest
    ports:
      - ${DB_SYNC_GRPC_PORT}:${DB_SYNC_GRPC_PORT}
    volumes:
      - ./proto/db-sync.proto:/app/proto/db-sync.proto
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  kwil-admin-2:
    image: martinopensky/kwil-admin:latest
    ports:
      - ${KWIL_ADMIN_PORT}:3000
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    restart: on-failure

  kwil-2:
    image: kwildb/kwil:latest
    ports:
      - ${EXTENSION_HELPERS_PORT}:${EXTENSION_HELPERS_PORT}
      - ${EXTENSION_DB_EXPORT_PORT}:${EXTENSION_DB_EXPORT_PORT}
      - ${EXTENSION_DB_SYNC_PORT}:${EXTENSION_DB_SYNC_PORT}
      - ${KWIL_PROVIDER_PORT}:8080
    env_file:
      - ./config/${PROVIDER_ENV_FILE}
    environment:
      - KWILD_EXTENSION_ENDPOINTS=extension-helpers-2:${EXTENSION_HELPERS_PORT},extension-db-export-2:${EXTENSION_DB_EXPORT_PORT},extension-db-sync-2:${EXTENSION_DB_SYNC_PORT}
    depends_on:
      - extension-helpers-2
      - extension-db-export-2
      - extension-db-sync-2
    restart: on-failure